### ISSUE TITLE
Certain fields should not require a player header

### ISSUE THREAD

**Issue by mabuyo** [mabuyo/demo-quizzes#3]
Querying for the following fields result in the error message "cannot find the player header".

- `allQuizzes`: anyone should be able to view the list of quizzes
- `createPlayer`: No player id to include in the header yet.

**Comment by bnjjj** [comment]
Thanks ! It has been fixed [here](https://github.com/mabuyo/demo-quizzes/commit/f96bf731ee9bfffe2c07d69be92f4187e2c06d0c)
